// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: listening_history.proto

package listening_history

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserListeningHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListeningHistoryRequest) Reset() {
	*x = GetUserListeningHistoryRequest{}
	mi := &file_listening_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListeningHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListeningHistoryRequest) ProtoMessage() {}

func (x *GetUserListeningHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listening_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListeningHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetUserListeningHistoryRequest) Descriptor() ([]byte, []int) {
	return file_listening_history_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserListeningHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListeningHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SongId        string                 `protobuf:"bytes,3,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	ListenedAtUtc *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=listened_at_utc,json=listenedAtUtc,proto3" json:"listened_at_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListeningHistoryItem) Reset() {
	*x = ListeningHistoryItem{}
	mi := &file_listening_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListeningHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListeningHistoryItem) ProtoMessage() {}

func (x *ListeningHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_listening_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListeningHistoryItem.ProtoReflect.Descriptor instead.
func (*ListeningHistoryItem) Descriptor() ([]byte, []int) {
	return file_listening_history_proto_rawDescGZIP(), []int{1}
}

func (x *ListeningHistoryItem) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ListeningHistoryItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListeningHistoryItem) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *ListeningHistoryItem) GetListenedAtUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.ListenedAtUtc
	}
	return nil
}

type GetUserListeningHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*ListeningHistoryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListeningHistoryResponse) Reset() {
	*x = GetUserListeningHistoryResponse{}
	mi := &file_listening_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListeningHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListeningHistoryResponse) ProtoMessage() {}

func (x *GetUserListeningHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listening_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListeningHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserListeningHistoryResponse) Descriptor() ([]byte, []int) {
	return file_listening_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserListeningHistoryResponse) GetItems() []*ListeningHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_listening_history_proto protoreflect.FileDescriptor

const file_listening_history_proto_rawDesc = "" +
	"\n" +
	"\x17listening_history.proto\x12\x11listening_history\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x1eGetUserListeningHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa7\x01\n" +
	"\x14ListeningHistoryItem\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\asong_id\x18\x03 \x01(\tR\x06songId\x12B\n" +
	"\x0flistened_at_utc\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlistenedAtUtc\"`\n" +
	"\x1fGetUserListeningHistoryResponse\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.listening_history.ListeningHistoryItemR\x05items2\x98\x01\n" +
	"\x13ListeningHistoryApi\x12\x80\x01\n" +
	"\x17GetUserListeningHistory\x121.listening_history.GetUserListeningHistoryRequest\x1a2.listening_history.GetUserListeningHistoryResponseBIZGlistening-history-service/pkg/proto/listening_history;listening_historyb\x06proto3"

var (
	file_listening_history_proto_rawDescOnce sync.Once
	file_listening_history_proto_rawDescData []byte
)

func file_listening_history_proto_rawDescGZIP() []byte {
	file_listening_history_proto_rawDescOnce.Do(func() {
		file_listening_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listening_history_proto_rawDesc), len(file_listening_history_proto_rawDesc)))
	})
	return file_listening_history_proto_rawDescData
}

var file_listening_history_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_listening_history_proto_goTypes = []any{
	(*GetUserListeningHistoryRequest)(nil),  // 0: listening_history.GetUserListeningHistoryRequest
	(*ListeningHistoryItem)(nil),            // 1: listening_history.ListeningHistoryItem
	(*GetUserListeningHistoryResponse)(nil), // 2: listening_history.GetUserListeningHistoryResponse
	(*timestamppb.Timestamp)(nil),           // 3: google.protobuf.Timestamp
}
var file_listening_history_proto_depIdxs = []int32{
	3, // 0: listening_history.ListeningHistoryItem.listened_at_utc:type_name -> google.protobuf.Timestamp
	1, // 1: listening_history.GetUserListeningHistoryResponse.items:type_name -> listening_history.ListeningHistoryItem
	0, // 2: listening_history.ListeningHistoryApi.GetUserListeningHistory:input_type -> listening_history.GetUserListeningHistoryRequest
	2, // 3: listening_history.ListeningHistoryApi.GetUserListeningHistory:output_type -> listening_history.GetUserListeningHistoryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_listening_history_proto_init() }
func file_listening_history_proto_init() {
	if File_listening_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listening_history_proto_rawDesc), len(file_listening_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listening_history_proto_goTypes,
		DependencyIndexes: file_listening_history_proto_depIdxs,
		MessageInfos:      file_listening_history_proto_msgTypes,
	}.Build()
	File_listening_history_proto = out.File
	file_listening_history_proto_goTypes = nil
	file_listening_history_proto_depIdxs = nil
}
