// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: listening_history.proto

package listening_history

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ListeningHistoryApi_GetUserListeningHistory_FullMethodName = "/listening_history.ListeningHistoryApi/GetUserListeningHistory"
)

// ListeningHistoryApiClient is the client API for ListeningHistoryApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListeningHistoryApiClient interface {
	GetUserListeningHistory(ctx context.Context, in *GetUserListeningHistoryRequest, opts ...grpc.CallOption) (*GetUserListeningHistoryResponse, error)
}

type listeningHistoryApiClient struct {
	cc grpc.ClientConnInterface
}

func NewListeningHistoryApiClient(cc grpc.ClientConnInterface) ListeningHistoryApiClient {
	return &listeningHistoryApiClient{cc}
}

func (c *listeningHistoryApiClient) GetUserListeningHistory(ctx context.Context, in *GetUserListeningHistoryRequest, opts ...grpc.CallOption) (*GetUserListeningHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserListeningHistoryResponse)
	err := c.cc.Invoke(ctx, ListeningHistoryApi_GetUserListeningHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListeningHistoryApiServer is the server API for ListeningHistoryApi service.
// All implementations must embed UnimplementedListeningHistoryApiServer
// for forward compatibility.
type ListeningHistoryApiServer interface {
	GetUserListeningHistory(context.Context, *GetUserListeningHistoryRequest) (*GetUserListeningHistoryResponse, error)
	mustEmbedUnimplementedListeningHistoryApiServer()
}

// UnimplementedListeningHistoryApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedListeningHistoryApiServer struct{}

func (UnimplementedListeningHistoryApiServer) GetUserListeningHistory(context.Context, *GetUserListeningHistoryRequest) (*GetUserListeningHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserListeningHistory not implemented")
}
func (UnimplementedListeningHistoryApiServer) mustEmbedUnimplementedListeningHistoryApiServer() {}
func (UnimplementedListeningHistoryApiServer) testEmbeddedByValue()                             {}

// UnsafeListeningHistoryApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListeningHistoryApiServer will
// result in compilation errors.
type UnsafeListeningHistoryApiServer interface {
	mustEmbedUnimplementedListeningHistoryApiServer()
}

func RegisterListeningHistoryApiServer(s grpc.ServiceRegistrar, srv ListeningHistoryApiServer) {
	// If the following call panics, it indicates UnimplementedListeningHistoryApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ListeningHistoryApi_ServiceDesc, srv)
}

func _ListeningHistoryApi_GetUserListeningHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListeningHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListeningHistoryApiServer).GetUserListeningHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListeningHistoryApi_GetUserListeningHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListeningHistoryApiServer).GetUserListeningHistory(ctx, req.(*GetUserListeningHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ListeningHistoryApi_ServiceDesc is the grpc.ServiceDesc for ListeningHistoryApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListeningHistoryApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "listening_history.ListeningHistoryApi",
	HandlerType: (*ListeningHistoryApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserListeningHistory",
			Handler:    _ListeningHistoryApi_GetUserListeningHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "listening_history.proto",
}
